services:
  axon-server:
    image: axoniq/axonserver:2024.0.2-jdk-17
    ports:
      - 8024:8024
      - 8124:8124
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password