spring:
  application:
    name: xpenser
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:user}
      password: ${MONGO_DB_PASSWORD:password}
      authentication-database: ${MONGO_DB_AUTHENTICATION_DB:admin}
      database: ${MONGO_DB_DATABASE_NAME:xpenser}

xpenser:
  currency:
    exchange:
      base-uri: ${OPEN_EXCHANGE_API_BASE_URI:https://openexchangerates.org/api/}
      app-id: ${OPEN_EXCHANGE_APP_ID}