spring:
  application:
    name: xpenser
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:user}
      password: ${MONGO_DB_PASSWORD:password}
      authentication-database: ${MONGO_DB_AUTHENTICATION_DB:admin}