spring:
  application:
    name: xpenser

axoniq:
  console:
    application-name: XPenser
    credentials: 01498322-0:5aa7a44016304205bf7c2e24b087bc7c
    dlq-mode: NONE


axon:
  serializer:
    general: jackson
springdoc:
  swagger-ui:
    config-url: http://localhost:8080/v3/api-docs
