package me.ezzedine.mohammed.xpenser.infra.persistence.expense.category.report;

import org.springframework.data.mongodb.repository.ReactiveMongoRepository;

public interface ExpenseCategoryMonthlyReportReactiveMongodbRepository extends ReactiveMongoRepository<ExpenseCategoryMonthlyReportDocument, ExpenseCategoryMonthlyReportDocument.CompositeKey> {
}
